### ISSUE TITLE
Config values ter-commit

### ISSUE THREAD

**Issue by hynra** [pptik/semut-tegar-security-rest-api#1]
Bro @fiyyanputra file confignya ke-commit, cek `/configs/database.json` sama `/configs/rmq.json` value `mongodb_uri` & `broker_uri`. Commit [2ab2bfc](https://github.com/pptik/semut-tegar-security-rest-api/commit/2ab2bfc69edfc5654ca106083edefa9bbd83149c) Bisa di revert kayak kasus kemaren ?

**Comment by fiyyanputra** [comment]
sudah di clean bro

**Comment by hynra** [comment]
👍
